export default {
  state: {
    atbashEncrypt: '',
    atbashAlphabet: {
      A: 'Z',
      B: 'Y',
      C: 'X',
      D: 'W',
      E: 'V',
      F: 'U',
      G: 'T',
      H: 'S',
      I: 'R',
      J: 'Q',
      K: 'P',
      L: 'O',
      M: 'N',
      N: 'M',
      O: 'L',
      P: 'K',
      Q: 'J',
      R: 'I',
      S: 'H',
      T: 'G',
      U: 'F',
      V: 'E',
      W: 'D',
      X: 'C',
      Y: 'B',
      Z: 'A',
      a: 'z',
      b: 'y',
      c: 'x',
      d: 'w',
      e: 'v',
      f: 'u',
      g: 't',
      h: 's',
      i: 'r',
      j: 'q',
      k: 'p',
      l: 'o',
      m: 'n',
      n: 'm',
      o: 'l',
      p: 'k',
      q: 'j',
      r: 'i',
      s: 'h',
      t: 'g',
      u: 'f',
      v: 'e',
      w: 'd',
      x: 'c',
      y: 'b',
      z: 'a',
      А: 'Я',
      Б: 'Ю',
      В: 'Э',
      Г: 'Ъ',
      Д: 'Ы',
      Е: 'Ь',
      Ё: 'Щ',
      Ж: 'Ш',
      З: 'Ч',
      И: 'Ц',
      Й: 'Х',
      К: 'Ф',
      Л: 'У',
      М: 'Т',
      Н: 'С',
      О: 'Р',
      П: 'П',
      Р: 'О',
      С: 'Н',
      Т: 'М',
      У: 'Л',
      Ф: 'К',
      Х: 'Й',
      Ц: 'И',
      Ч: 'З',
      Ш: 'Ж',
      Щ: 'Ё',
      Ь: 'Е',
      Ы: 'Д',
      Ъ: 'Г',
      Э: 'В',
      Ю: 'Б',
      Я: 'А',
      а: 'я',
      б: 'ю',
      в: 'э',
      г: 'ъ',
      д: 'ы',
      е: 'ь',
      ё: 'щ',
      ж: 'ш',
      з: 'ч',
      и: 'ц',
      й: 'х',
      к: 'ф',
      л: 'у',
      м: 'т',
      н: 'с',
      о: 'р',
      п: 'п',
      р: 'о',
      с: 'н',
      т: 'м',
      у: 'л',
      ф: 'к',
      х: 'й',
      ц: 'и',
      ч: 'з',
      ш: 'ж',
      щ: 'ё',
      ь: 'е',
      ы: 'д',
      ъ: 'г',
      э: 'в',
      ю: 'б',
      я: 'а',
    },
  },
  mutations: {
    setAtbashEncrypt(state, payload) {
      state.atbashEncrypt = payload;
    },
  },
  actions: {
    setAtbashEncrypt({commit, getters}, payload) {
      const atbashAlphabet = getters.getAtbashAlphabet;
      let decodedStr = '';

      for (let i = 0; i < payload.length; i++) {
        if (!atbashAlphabet[payload[i]]) {
          decodedStr += payload[i];
        } else {
          decodedStr += atbashAlphabet[payload[i]];
        }
      }

      commit('setAtbashEncrypt', decodedStr);
    },
  },
  getters: {
    getAtbashAlphabet(state) {
      return state.atbashAlphabet;
    },
    getAtbashEncrypt(state) {
      return state.atbashEncrypt;
    },
  },
};
